DROP DATABASE IF EXISTS UsageMntrServDB;
CREATE DATABASE UsageMntrServDB;
USE UsageMntrServDB;


CREATE TABLE Logs(
user_id INT,
video VARCHAR (255),
info VARCHAR(100),
dtime DATETIME DEFAULT CURRENT_TIMESTAMP
);


