DROP DATABASE IF EXISTS UsageMntrServDB;
CREATE DATABASE UsageMntrServDB;
USE UsageMntrServDB;


CREATE TABLE Logs(
ID INT AUTO_INCREMENT PRIMARY KEY,
info VARCHAR(255),
dtime DATETIME DEFAULT CURRENT_TIMESTAMP
);


